#!/bin/sh
# The IKE Scanner (ike-scan) is Copyright (C) 2003-2007 Roy Hills,
# NTA Monitor Ltd.
#
# This file is part of ike-scan.
#
# ike-scan is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ike-scan is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ike-scan.  If not, see <http://www.gnu.org/licenses/>.
#
# check-run3 -- Shell script to test ike-scan's lists
#
# Author: Roy Hills
# Date: 13 January 2004
#
# This shell script runs ike-scan with the highest verbose level to display
# the contents of the internal lists: the host list, the backoff list, and
# the vendor id patterns list.  It then checks that all of these lists are
# displayed.
#
TMPFILE=/tmp/ike-scan-test.$$.tmp
#
echo "Checking ike-scan internal lists ..."
$srcdir/ike-scan --nodns --sport=0 --dport=33434 -v -v -v --showbackoff \
   --retry=1 --patterns=$srcdir/ike-backoff-patterns \
   --vidpatterns=$srcdir/ike-vendor-ids 127.0.0.1 >$TMPFILE 2>&1
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - ike-scan returned non-zero exit code"
   exit 1
fi
grep '^Total of [0-9]* host entries\.$' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - host list summary not found"
   exit 1
fi
grep '^Total of [0-9]* backoff pattern entries\.$' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - backoff list summary not found"
   exit 1
fi
grep '^Total of [0-9]* Vendor ID pattern entries\.$' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - vendor id list summary not found"
   exit 1
fi
echo "ok"
#
rm -f $TMPFILE
