#!/bin/sh
# The IKE Scanner (ike-scan) is Copyright (C) 2003-2007 Roy Hills,
# NTA Monitor Ltd.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# check-run2 -- Shell script to test ike-scan to localhost
#
# Author: Roy Hills
# Date: 13 January 2004
#
# This shell script runs ike-scan against a port on localhost (127.0.0.1),
# which is unlikely to be listening, and checks that it reports correctly.
#
TMPFILE=/tmp/ike-scan-test.$$.tmp
#
echo "Checking ike-scan --sport=0 --dport=33434 127.0.0.1 ..."
$srcdir/ike-scan --nodns --retry=1 --sport=0 --dport=33434 127.0.0.1 >$TMPFILE 2>&1
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^Ending ike-scan.* 0 returned handshake; 0 returned notify$' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
rm -f $TMPFILE
